version: 1.0.{build}
pull_requests:
  do_not_increment_build_number: true
branches:
  only:
  - master
skip_branch_with_pr: true
image: Visual Studio 2022
dotnet_csproj:
  patch: true
  file: '**\*.csproj'
  version: '{version}'
  version_prefix: '{version}'
  package_version: '{version}'
  assembly_version: '{version}'
  file_version: '{version}'
  informational_version: '{version}'
environment:
  CI: false
cache:
- C:\ProgramData\chocolatey\bin
- C:\ProgramData\chocolatey\lib
build_script:
- ps: >-
    .\Scripts\appveyor-build.ps1
