blank_issues_enabled: false
contact_links:
  - name: 💬 Feature Requests & Questions
    url: https://github.com/replaysMike/SystemMonitor/discussions
    about: Please ask and answer questions here, but don't report bugs here! That's what bug reports/issues are for!
